Upgraded to JDK 17 using OpenRewrite.
1. Successfully upgraded to JDK 17 using OpenRewrite "org.openrewrite.java.migrate.UpgradeToJava17" recipe.

2. Fixed issues with JAXB support. Compiles successfully, however unit tests fail with "Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException". As such, we need to upgrade to Spring Boot 3.x.x version.

3. Upgraded the "wro4j-maven-plugin" library to version "2.1.1".

4. Fixed some other unit tests that were failing.

NOTE: This was done using JDK 1.8 configured on the IDE project settings. Once completed, had to switch to JDK 17 on the IDE project settings.